/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Dlink */

#ifndef _Included_Dlink
#define _Included_Dlink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Dlink
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Dlink_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Dlink
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Dlink_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Dlink
 * Method:    mult
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Dlink_mult
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Dlink
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Dlink_div
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
